version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  publish:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10.15.0
    steps:
    - attach_workspace:
        at: ~/repo
    - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
    - run:
        name: Publish package
        command: npm publish
workflows:
  version: 2
  test-deploy:
    jobs:
    - test:
        filters:
          tags:
            only: /^v.*/
    - publish:
        requires:
        - test
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
