name: Build and Test
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      
      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Yarn install
        run: yarn
      
      - name: Build project and test
        run: yarn test
      
      - name: Run benchmarks
        run: node tests/run-bench tests/Benchmarks/YGBenchmark.js
